name: simple_dart_list_field
description: ListField Component
version: 0.0.3
repository: https://github.com/simple-dart/list_field
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  simple_dart_image_button: ^0.0.1
  simple_dart_label: ^0.0.1
  simple_dart_text_field: ^0.0.3
  simple_dart_ui_core: ^0.0.2
